### ISSUE TITLE
Fix duplicate integrity attribute

### ISSUE THREAD

**Issue by XhmikosR** [ScottHelme/securityheaders-bugs#1]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fsecurityheaders.io%2F

The rest of the validation errors is up to you :)

**Comment by ScottHelme** [comment]
This should now be fixed on the test site: https://validator.w3.org/nu/?doc=https%3A%2F%2Ftest.securityheaders.io

If you're happy with the fix then feel free to close the issue and the changes will be pushed to the live site.

**Comment by XhmikosR** [comment]
Is the source available? If not, have you thought about open sourcing it?

**Comment by ScottHelme** [comment]
It's not open at the minute. I have thought about the idea but I've not given it any real thought yet to make a decision.

**Comment by XhmikosR** [comment]
This issue is resolved.

Please consider open sourcing the repo for further improvements from the community,
