### ISSUE TITLE
Contextual grading in CSP

### ISSUE THREAD

**Issue by aidantwoods** [ScottHelme/securityheaders-bugs#10]
HSTS and HPKP already have contextual grading.
In my opinion contextual wild cards on active content in CSP, including 'unsafe-inline' and 'unsafe-eval' should probably cap the grade, or issue at least issue a warning.

E.g. Would it would currently be possible to raise your grade by specifying a CSP that allows everything? (and is thus useless)

**Comment by ScottHelme** [comment]
I've made some changes on the test site so there are now a couple of warnings:

https://test.securityheaders.io/?q=https%3A%2F%2Fscotthelme.co.uk%2F&followRedirects=on

Still early work but it's in the right direction.

**Comment by aidantwoods** [comment]
Looking good!

Here I've setup a page with a bad CSP (that's useless) [Grade A]
https://test.securityheaders.io/?q=https%3A%2F%2Fwww.aidanwoods.com%2Fbad-csp&hide=on&followRedirects=on

And a page with no CSP (equally useless) [Grade B]
https://test.securityheaders.io/?q=https%3A%2F%2Fwww.aidanwoods.com%2Fno-csp&hide=on&followRedirects=on

IMO they should get the same grade – though not sure how feasible it would be to actually evaluate the CSP at that level without building at least a semi capable parser for it. 

(Not sure if it would help – I've got a regex hanging around somewhere that does the work of splitting directives and values. Would reduce the problem to an easily iterable check like `if(in_array("*", csp['script-src'])) doSomething();`, `if(in_array("'unsafe-inline'", csp['script-src'])) doSomething();` etc... so you could at least narrow the search by directive, rather than searching the whole CSP string)

**Comment by ScottHelme** [comment]
I'm going to close this one for now but please feel to open if you have further comments.

**Comment by aidantwoods** [comment]
Just a minor one, RE the actual grade cap ;p

'Bad' CSPs are capped at A, while no CSP is capped at B. (I think this is still true?)

The A+ grade is reserved for sites that implement HPKP (which isn't safe/feasible for a huge amount of sites – but then, that's why it has the top grade). Deploying an effective CSP on the other hand (while possibly difficult) isn't unsafe (like accidental 60 days self-DOS kinda unsafe). 

At the moment having a good CSP and deploying HPKP are awarded the same (since they only cap you from the A+ grade), but IMO distinguishing an effective CSP from an ineffective one is something that should appear lower down on the scale. 

(i.e. those who produce good CSPs should appear above those who produce bad ones, and CSPs that aren't trivial to bypass should be considered more important than HPKP).

Just my 2 cents anyway :)

**Comment by ScottHelme** [comment]
I thought about dropping the current cap on a bad CSP to B but then there are other considerations like the research Google did in their recent CSP whitepaper. Dropping it based purely on unsafe-\* would be a first step but I'd need to basically implement the Google checks to pick up a 'bad CSP' but even then, it's not exhaustive. 

The primary goal of the site is to educate people, the "definitive" security assessment is a secondary objective. I am of course always increasing the standard, but grading CSP is a messy game :)

**Comment by aidantwoods** [comment]
Definitely right about CSP grading being non-trivial! I suppose I was thinking more along the lines that if you can know that the CSP is bad, then mark it down – but then again, maybe the warning is enough for a learning tool. 

Are there any plans to give out similar warnings based on wildcard inclusions? (`http:`, `https:`, `data:`, `*`, etc...)

**Comment by ScottHelme** [comment]
I'm tempted to allow wildcard subdomains to pass, but then I see a lot of policies with https: where their goal is clearly to fix mixed content. I'm not sure if a site should be penalised for using CSP to fix mixed content. CSP is multi-purpose, I think grading it based on XSS protection only doesn't do it justice.

**Comment by aidantwoods** [comment]
That's a good point, though I suppose you could make a similar argument for `'unsafe-inline'` – a site wants to limit where their page can talk to, but can't quite nonce/hash/whitelist all their scripts. They're still utilising CSP to prevent data leakage, but can't quite do the anti-XSS bit yet.

Shouldn't these cases be treated the same (can achieve an A, but not A+, and give warning about the wildcard/`'unsafe-*'`).

Totally with you on allowing wildcard subdomains, also something like `https://example.com/*` should be allowed (since it's treated the same as `https://example.com`)

I reckon this is pretty close to covering most bases https://regex101.com/r/eIxebE/2
(highlighted is an identified wildcard, no highlight is 'specific enough' not to be a wildcard).

**Comment by aidantwoods** [comment]
Plus, we have `upgrade-insecure-requests` and `block-all-mixed-content` for avoiding mixed content without the wildcard ;p 
That said, I suppose you could allow `https:` but still warn about the other wildcards

**Comment by aidantwoods** [comment]
[This is what I settled on](https://github.com/aidantwoods/SecureHeaders/commit/d83bc2d917dd79dc7ed950ec468375aaae74fad7), needed to re-write that regex anyway.

Contrary to the one in the previous comment, I decided not to explicitly fault a wildcard port if a domain is specified, [some test data here](https://regex101.com/r/erzriS/1)
