### ISSUE TITLE
Don't require redundant STS on preloaded TLDs

### ISSUE THREAD

**Issue by Seirdy** [ScottHelme/securityheaders-bugs#104]
Several TLDs are in the HSTS Preload list by default. The ones I'm aware of are:

gle .prod .docs .cal .soy .how .chrome .ads .mov .youtube .channel .nexus .goog .boo .dad .drive .hangout .new .eat .app .moto .ing .meme .here .zip .guge .car .foo .day .dev .play .gmail .fly .gbiz .rsvp .android .map .page .google .dclk .search .prof .phd .esq .みんな .谷歌 .グーグル

An HSTS header would be redundant on these domains, since they are all preloaded.

**Comment by ScottHelme** [comment]
The client may not implement the preload list or have an updated copy of the preload list. Many clients speak TLS/HTTP that are not web browsers too. Given the low/no impact of setting the header, and that possible benefits exist for setting it, the requirement for a HSTS header will likely remain.
