### ISSUE TITLE
[feature] Custom User-Agent String

### ISSUE THREAD

**Issue by andrdrou** [ScottHelme/securityheaders-bugs#105]
Right now security headers scan get blocked by our Cloudflare Bot filter.
Would it be possible to add/use custom User-Agent Header to filter it out by, instead of using whitelisting IP's?

**Comment by ScottHelme** [comment]
Our FAQ contains information on what our current UA string is, so you should be able to identify us with that, but we don't have plans to add a custom UA string option at this time: https://securityheaders.com/faq/
