### ISSUE TITLE
When there is more than one HSTS header, this is not reflected

### ISSUE THREAD

**Issue by hmallett** [ScottHelme/securityheaders-bugs#11]
If a site is misconfigured, and presenting more than one HSTS header, then securityheaders does not reflect this, and reports only one of the headers, with no indication that there are any more.
For comparison, SSLLabs will highlight that the server provided more than one HSTS header.

**Comment by ScottHelme** [comment]
I've pushed a patch to the test site, can you try it out there?

https://test.securityheaders.io/

**Comment by hmallett** [comment]
My example now shows a warning for any duplicate headers, not just HSTS.
