### ISSUE TITLE
Integrate with CI build

### ISSUE THREAD

**Issue by davidwestonuk** [ScottHelme/securityheaders-bugs#13]
Currently we use jenkins jobs to validate our sites and it would be great if we could include a check against this as part of our QA process.

Have you considered creating a jenkins plugin?

**Comment by ScottHelme** [comment]
I haven't considered a plugin for Jenkins but if you're interested in making one, you can fetch your results easily. 

```
curl -I -X HEAD https://securityheaders.io/?q=https%3A%2F%2Fscotthelme.co.uk%2F&followRedirects=on
```

Simply issue a HEAD request against the results page you want the score for and look at the headers. You can use the following:

```
X-Score: eyJzY29yZSI6IkErIiwgImNvbG91ciI6ImxpZ2h0Z3JlZW4ifQ==
X-Grade: A+
```

If you simply want the grade then the X-Grade header will do. If not, you can base64 decode the X-Score header.

**Comment by ScottHelme** [comment]
Closing and hoping the above was enough to satisfy the requirement.
