### ISSUE TITLE
Add "kestrel" to known server headers

### ISSUE THREAD

**Issue by ChiefWiggum** [ScottHelme/securityheaders-bugs#14]
The aspnet.core webserver [kestrel](https://github.com/aspnet/KestrelHttpServer) is marked as a changed server header. I suggest adding it to the known server headers.

**Comment by ScottHelme** [comment]
This is fixed on the test site, can you confirm for me?

https://test.securityheaders.io

**Comment by ChiefWiggum** [comment]
Excellent, that works as expected. Ideally you could also add a description of how to remove it. I haven't tried [this](https://github.com/aspnet/KestrelHttpServer/pull/855), but assume that should to the trick.

In any case,
Thanks for the fast response and fix!
