### ISSUE TITLE
Add CSP meta-tag recognition

### ISSUE THREAD

**Issue by Y90SMH** [ScottHelme/securityheaders-bugs#15]
Just wondering if adding support for the CSP html meta tag would be beneficial for users to see on their report.

It could be shown with a caution next to it as the preferred method would be through the response header.

Thoughts?

**Comment by ScottHelme** [comment]
I have thought about this before but it seems to be stepping outside of what I created the site for, which was to analyse HTTP response headers. I'm not sure I want to start down that road :-)

**Comment by ScottHelme** [comment]
After giving this some more thought I've decided not to implement meta-tag support right now.
