### ISSUE TITLE
Ignore unknown HSTS directives

### ISSUE THREAD

**Issue by tomrittervg** [ScottHelme/securityheaders-bugs#16]
Currently I believe it doesn't count a HSTS header if it contains an unknown directive. Unknown directives are permitted by the spec, and if you can't process them you ignore them.

**Comment by ScottHelme** [comment]
This should be fixed on the test site, https://test.securityheaders.io, could you test it for me?

**Comment by tomrittervg** [comment]
Looks like it! https://test.securityheaders.io/?q=https%3A%2F%2Fritter.vg&followRedirects=on

**Comment by ScottHelme** [comment]
This should be in production soon, closing this issue.
