### ISSUE TITLE
CSP invalid syntax check

### ISSUE THREAD

**Issue by spaze** [ScottHelme/securityheaders-bugs#18]
[This CSP header](https://securityheaders.io/?q=https%3A%2F%2Fib.sms.mpu.cz%2Fprihlaseni%2Fsms&followRedirects=on) is missing directive separators:
`default-src 'self' script-src 'self' 'unsafe-eval' style-src 'self' 'unsafe-inline';`
A check for such case would be nice.

Chrome does that and throws the following warning in console:
`The Content Security Policy directive 'default-src' contains 'script-src' as a source expression. Did you mean 'default-src ...; script-src...' (note the semicolon)?`

So the check could be modeled after the Chrome's one.

Thanks for considering this!

**Comment by ScottHelme** [comment]
Good catch, I should be able to detect this!

**Comment by ScottHelme** [comment]
This is now live on the test site and should hit prod soon. Closing issue :)

**Comment by spaze** [comment]
Perfect, thanks @ScottHelme!
