### ISSUE TITLE
Maybe soften recommendation for X-XSS-Protection?

### ISSUE THREAD

**Issue by tbroyer** [ScottHelme/securityheaders-bugs#19]
The blog post at http://blog.innerht.ml/the-misunderstood-x-xss-protection/ argues that you should rather set `X-XSS-Protection` to `0` (and be XSS-free, of course) than to `X-XSS-Protection: 1; mode=block`, as the later introduces(d?) new vulnerabilities.

In “Additional Information” securityheaders.io gives this recommendation: “The best configuration is "X-XSS-Protection: 1; mode=block".”

Maybe this should be reworded a bit?

(I noted that `X-XSS-Protection: 0` still is OK per securityheaders.io, as [Facebook is rated with an A](https://schd.io/3j) with this header; this issue is not a report about the treatment of the header, only about the text recommending `1; mode=block` as “the best configuration”)

**Comment by ScottHelme** [comment]
Yeah, I allow `X-XSS-Protection: 0` as there are those who are brave enough to go into the world with no protection and have enough confidence in their own XS protections. That said, for the rest of us `X-XSS-Protection: 1; mode=block` is far better than `X-XSS-Protection: 1` which is the default and the most dangerous. It's a tough one

**Comment by ScottHelme** [comment]
If there is a followup please feel free to open the issue again :)
