### ISSUE TITLE
CSP: Mark start of sub-tags and important sub-clauses

### ISSUE THREAD

**Issue by BenBE** [ScottHelme/securityheaders-bugs#20]
To improve readability of CSP headers it might be good to mark the start of each tag (e.g. default-src, script-src, ...) in bold to ease orientation.

Optional / up for consideration:
Further marking of unsafe-inline, unsafe-eval and data: might be up for consideration (underlined, red) vs. 'none' and 'self', also maybe same-origin HTTPS (italic, blue*).

*to avoid color perception issues; otherwise green is fine too.

Example:

Tags only:
> **default-src** 'none'; **script-src** 'self' cdnjs.cloudflare.com code.jquery.com scotthelme.disqus.com a.disquscdn.com www.google-analytics.com go.disqus.com platform.twitter.com cdn.syndication.twimg.com; **style-src** 'self' a.disquscdn.com fonts.googleapis.com cdnjs.cloudflare.com platform.twitter.com; **img-src** 'self' data: www.gravatar.com www.google-analytics.com links.services.disqus.com referrer.disqus.com a.disquscdn.com cdn.syndication.twimg.com syndication.twitter.com pbs.twimg.com platform.twitter.com abs.twimg.com; **child-src** fusiontables.googleusercontent.com fusiontables.google.com www.google.com disqus.com www.youtube.com syndication.twitter.com platform.twitter.com; **frame-src** fusiontables.googleusercontent.com fusiontables.google.com www.google.com disqus.com www.youtube.com syndication.twitter.com platform.twitter.com; **connect-src** 'self' links.services.disqus.com; **font-src** 'self' cdnjs.cloudflare.com fonts.gstatic.com fonts.googleapis.com; **form-action** 'self'; **upgrade-insecure-requests**; **report-uri** https://scotthelme.report-uri.io/r/default/csp/enforce

Additional coding of attributes:
> **default-src** _'none'_; **script-src** _'self'_ cdnjs.cloudflare.com code.jquery.com scotthelme.disqus.com a.disquscdn.com www.google-analytics.com go.disqus.com platform.twitter.com cdn.syndication.twimg.com; **style-src** _'self'_ a.disquscdn.com fonts.googleapis.com cdnjs.cloudflare.com platform.twitter.com; **img-src** _'self'_ **data:** www.gravatar.com www.google-analytics.com links.services.disqus.com referrer.disqus.com a.disquscdn.com cdn.syndication.twimg.com syndication.twitter.com pbs.twimg.com platform.twitter.com abs.twimg.com; **child-src** fusiontables.googleusercontent.com fusiontables.google.com www.google.com disqus.com www.youtube.com syndication.twitter.com platform.twitter.com; **frame-src** fusiontables.googleusercontent.com fusiontables.google.com www.google.com disqus.com www.youtube.com syndication.twitter.com platform.twitter.com; **connect-src** _'self'_ links.services.disqus.com; **font-src** _'self'_ cdnjs.cloudflare.com fonts.gstatic.com fonts.googleapis.com; **form-action** _'self'_; **upgrade-insecure-requests**; **report-uri** https://scotthelme.report-uri.io/r/default/csp/enforce

**Comment by ScottHelme** [comment]
I like the idea. I've added it to The List of Things To Do (TM). :)

**Comment by ScottHelme** [comment]
This is now live on the test site and will hit production on the next push. Closing issue :)
