### ISSUE TITLE
PKP: Wrap per sub-tag

### ISSUE THREAD

**Issue by BenBE** [ScottHelme/securityheaders-bugs#21]
PKP header values should be word-wrapped per sub-tag to help visual parsing of the included attributes.

> pin-sha256="9dNiZZueNZmyaf3pTkXxDgOzLkjKvI+Nza0ACF5IDwg="; pin-sha256="X3pGTSOuJeEVw989IJ/cEtXUEmy52zs1TZQrU06KUKg="; pin-sha256="V+J+7lHvE6X0pqGKVqLtxuvk+0f+xowyr3obtq8tbSw="; pin-sha256="9lBW+k9EF6yyG9413/fPiHhQy5Ok4UI5sBpBTuOaa/U="; pin-sha256="ipMu2Xu72A086/35thucbjLfrPaSjuw4HIjSWsxqkb8="; includeSubDomains; max-age=2592000; report-uri="https://scotthelme.report-uri.io/r/default/hpkp/enforce"

Becomes:
> pin-sha256="9dNiZZueNZmyaf3pTkXxDgOzLkjKvI+Nza0ACF5IDwg=";
> pin-sha256="X3pGTSOuJeEVw989IJ/cEtXUEmy52zs1TZQrU06KUKg=";
> pin-sha256="V+J+7lHvE6X0pqGKVqLtxuvk+0f+xowyr3obtq8tbSw=";
> pin-sha256="9lBW+k9EF6yyG9413/fPiHhQy5Ok4UI5sBpBTuOaa/U=";
> pin-sha256="ipMu2Xu72A086/35thucbjLfrPaSjuw4HIjSWsxqkb8=";
> includeSubDomains;
> max-age=2592000;
> report-uri="https://scotthelme.report-uri.io/r/default/hpkp/enforce"

**Comment by ScottHelme** [comment]
Could we not say the same for CSP or use a similar approach like making the directives bold?

**Comment by ScottHelme** [comment]
I've added the bold syntax highlighting to HPKP and had a play with putting the pin values on a new line or not breaking, but I'm not too sure on that. I will close this for now but feel free to comment further :)
