### ISSUE TITLE
Set-Cookies - Sometimes yellow, sometimes black?

### ISSUE THREAD

**Issue by qJake** [ScottHelme/securityheaders-bugs#22]
I'm sure there's a reason for it but I don't see it in the documentation (and it doesn't appear to affect the grade), but why are some Set-Cookies definitions highlighted in yellow, while others are black?

For example, if we're talking about an ASP.NET Core site deployed in Azure:

These are black:

    Set-Cookie: .AspNetCore.Antiforgery.xxxxxxxxxxx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; path=/; httponly
    Set-Cookie: ARRAffinity=xxxxxxxxxxxxxxxxxxxPath=/;Domain=my.website.com

This one is yellow:

    Set-Cookie: .AspNetCore.Session=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; path=/; httponly

The "xxxxxxx" values are randomly-generated alphanumeric tokens created by ASP.NET Core.

What's the reason for this? Is it a bug?

**Comment by ScottHelme** [comment]
If the cookie is highlighted yellow then there should be an associated entry in the "Warnings" section to explain why. Do you have links to the specific results that I can look at?

These warnings currently don't affect your grade. I'm introducing the checks initially to gather information on frequency and what the impact is, I may then introduce a grading component later.

**Comment by qJake** [comment]
I would prefer to keep the site I tested with private (it's still under development), however our main website exhibits the same behavior:

https://securityheaders.io/?q=https%3A%2F%2Fwww.csiinc.com&hide=on

Ignore the other warnings (we've got some work to do obviously!), but as you can see, one "Set-Cookie" is black, the other is yellow, and there is seemingly no indication or warning as to why. This is the same as the private site I was testing against.

It seems to be related to the ASP.NET Session cookie. I wonder why that's getting flagged, specifically?

**Comment by ScottHelme** [comment]
Interesting. It's because I'm detecting it's a session cookie that doesn't have the `secure` flag set on a HTTPS website. For some reason though the associated warning isn't being shown! I will debug further.

**Comment by ScottHelme** [comment]
This is now fixed on the test site, can you check it over? 

https://test.securityheaders.io/?q=https%3A%2F%2Fwww.csiinc.com&hide=on

**Comment by qJake** [comment]
Yep, looks good! Tested it with the other site we have, too (both are ASP.NET Session cookies from different versions of ASP.NET). 👍

**Comment by ScottHelme** [comment]
Awesome, I'm working on a few other fixes and features so this will make it onto the live site with them. Thanks!

**Comment by ScottHelme** [comment]
I'm going to close this issue now, the fix will hit prod on the next push. Cheers.
