### ISSUE TITLE
Feature request: Email monitoring

### ISSUE THREAD

**Issue by da2x** [ScottHelme/securityheaders-bugs#23]
Let me pay you a one-time fee (please no more subscriptions!) per domain to monitor my domains and email me if my security rating drop, or there is significant development in the “security header” field. Maybe get something good going in partnership with [SSLPing](https://sslping.com/).

**Comment by ScottHelme** [comment]
A one-time fee doesn't really fit very well with an ongoing service. What I would recommend taking a look at is: https://www.hardenize.com/

securityheaders.io will always be free and I don't plan to introduce options that cost.
