### ISSUE TITLE
Enhancement: Test all A/AAAA records for a given domain

### ISSUE THREAD

**Issue by da2x** [ScottHelme/securityheaders-bugs#24]
Currently, securityheaders.io will look up a domain and only test one of the DNS records (in one IP family).

Should at least test one from each family (IPv4 and IPv6 – A/AAAA) as these may be served from differently configured servers. For comparison, the [Qualsys SSL Server Test](https://www.ssllabs.com/ssltest/) will check every A and AAAA record in DNS individually. Connect to the domain, but bind to specific IP address.

Take it a step further: Check DNS from multiple geographical locations (at least “US east coast, central Europe, and south Asia”), and combine all the DNS records. With Anycast DNS, different geographical (well, network topological) areas of the world will get different DNS responses pointing to servers nearest the user.

Please concatenate the reports if the servers are configured the same way. No need to list multiple test results if they’re the same.

**Comment by ScottHelme** [comment]
We aren't likely to introduce this feature in the immediate future.
