### ISSUE TITLE
Enhancement: Need more info and examples about each header to make a decision to include it

### ISSUE THREAD

**Issue by da2x** [ScottHelme/securityheaders-bugs#25]
For the links in the “Missing Headers” section of the report:

* Include spec source links (either right there in the report or more prominently on your own gateway pages).
* Include example scenario when not having the header fixes a problem on your website.
* Include another example scenario when adding the header causes a problem on your website.

**Comment by da2x** [comment]
Back story: The report shows me that I’m “missing” five out of six headers. Even as a security minded individual and sysadmin, nothing I’ve been shown on securityheaders.io report suggests that adding these headers would be of any benefit.

Concerns:

* Wouldn’t setting “X-Frame-Options” block my site from Bing/Google Translate? and StumbleUpon?
* What about my ads if I set Content-Security-Policy?
* Isn’t X-XSS-Protection the same as Content-Security-Policy in reverse?
* How do I automate HPKP to work when using certbot (for Let’s Encrypt) and AWS Route 53? other DNS providers/CAs?

**Comment by t-richards** [comment]
Enhancements to the warnings section would be appreciated as well.

For example, given the following scan results:
># Warnings
>
>**Referrer-Policy**&nbsp;&nbsp;&nbsp;&nbsp;The "origin-when-cross-origin" value is not recommended.

What is the recommended value, then? Is `same-origin` acceptable, or do I need to go all the way to `no-referrer`?

**Comment by fengerzh** [comment]
`same-origin` is ok.

**Comment by ScottHelme** [comment]
Closing issue as legacy.
