### ISSUE TITLE
A+ rating for non-SSL / https websites

### ISSUE THREAD

**Issue by optimalisatie** [ScottHelme/securityheaders-bugs#26]
Hi!

I am a long term user and promotor of the securityheaders.io service. It is a great start point for internet users seeking to achieve good quality security for their website.

There is one aspect however that appears to be misleading to users. Websites without SSL are able to obtain an A+ score more easily.

SSL is becoming more and more important for both security and SEO. Google has started to show an `insecure` warning for websites without SSL in the Google Chrome browser and in the search results of several countries.

https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html

![Google Chrome non-SSL Warning](https://3.bp.blogspot.com/-DG70U0Y-y9w/V9Cwuym53AI/AAAAAAAAAW0/6zO81T_hqWMjdAF_YYK7dfXV-26DL7OYACLcB/s400/blog%2Bimage%2B2.png)

It would be nice if the availability of SSL would become a (major) factor in the score.

Best Regards,
Jan Jaap

**Comment by aidantwoods** [comment]
This makes sense IMO!

e.g. this santander page (if it is indeed the legitimate site) gets an A grade on securityheaders
https://securityheaders.io/?q=http%3A%2F%2Fwww.ri.santander.com.br%2F

despite it coming over HTTP

<img width="1222" alt="screen shot 2017-05-15 at 22 28 50" src="https://cloud.githubusercontent.com/assets/3288888/26080343/00966ad2-39be-11e7-89c1-0b0881002d55.png">

Also they set a session cookie over HTTP. Security headers would mark it down if it was coming over HTTPS without the secure flag.

Wouldn't this site get more warnings if it was served over HTTPS? I can think of at least that cookie warning, as well as having no HSTS. That doesn't seem to make sense to me.

IMO sites that serve HTTP without a redirect to HTTPS should get a pretty significant grade cap. If they don't serve HTTPS, or serve it and have it 301 back to HTTP (santander.co.uk does this) then they should get an F grade IMO.

Also might be worth trying port 80 when HTTPS is scanned to see if it sends session cookies over HTTP.

**Comment by ScottHelme** [comment]
I see what you're both saying, and I do agree completely, my hang up is on whether security headers should be assessing your TLS implementation.

Most of the headers shouldn't be set over HTTP, like HSTS and HPKP, which is why it's easier to get higher grades on HTTP. I guess any of them are arguably useless over HTTP like CSP, as it can be modified in transit so the browser never even gets the CSP. This is probably the basis on which I'd implement a grade cap. Let me take a look at this more closely, I also have a couple of other updates to add soon.

**Comment by aidantwoods** [comment]
> I see what you're both saying, and I do agree completely, my hang up is on whether security headers should be assessing your TLS implementation.

I think the extent of the testing should be checking whether a connection is possible, as well as conditions on whether a redirect to (or from) HTTPS exists. Leave implementation specifics to somewhere that's dedicated to test for them – it's a service in itself to check all that.

**Comment by aidantwoods** [comment]
You could give the reasoning as something like "SecurityHeaders.io was unable to verify the authenticity of the response headers because the server responded insecurely" 😉 make it sound really bad (it is!)

Maybe grade `N` for "Not secure" (or "Not even trying" 😉 )

**Comment by optimalisatie** [comment]
It may be an option to integrate the SSLLabs.com API to encourage users to optimize SSL security. SSLLabs also uses an F-A+ rating. 

https://www.ssllabs.com/projects/ssllabs-apis/index.html

![ssllabs](https://cloud.githubusercontent.com/assets/8843669/26145319/5832f132-3aec-11e7-8399-fc5e0f708435.png)

**Comment by ScottHelme** [comment]
HTTPS is now part of the grading criteria.
