### ISSUE TITLE
4xx errors should probably not be graded

### ISSUE THREAD

**Issue by phils** [ScottHelme/securityheaders-bugs#29]
Tested a site that returned a 429 error code, and the site was graded F (missing everything).  Suggest this should just be considered an error rather than a valid page to give a grade to.

**Comment by aidantwoods** [comment]
Just bringing up a counter point that a site that has XSS in an error message with a 500 response would benefit from a CSP, but might not be so crucial HSTS is sent on this one error page for example.

**Comment by ScottHelme** [comment]
If it's returning text/html then there's not really any difference between a 200 or 400/500 response code.
