### ISSUE TITLE
CSP information given more than once

### ISSUE THREAD

**Issue by fuglede** [ScottHelme/securityheaders-bugs#30]
When a CSP is split across several lines (which is [allowed](https://www.w3.org/TR/2012/CR-CSP-20121115/#policy-delivery)), the "Additional Information" section gives its info on CSP more than once:

![csp](https://cloud.githubusercontent.com/assets/6169306/25096138/89b8c7a6-238e-11e7-9401-3d08aa7b11b6.png)

Edit: In fact, securityheaders.io reports the warning "There was a duplicate Content-Security-Policy header." in this case; it probably shouldn't?

**Comment by ScottHelme** [comment]
This should be fixed on the test site, can you confirm? 

https://test.securityheaders.com/

**Comment by fuglede** [comment]
I'm unable to reproduce the warning (on both test and the main site), but the "Additional settings" still contains duplicate entries; see e.g. https://test.securityheaders.com/?q=fuglede.dk&followRedirects=on

(Note that I can't reopen this issue.)
