### ISSUE TITLE
Don't warn about valid duplicate for referrer policy header

### ISSUE THREAD

**Issue by aidantwoods** [ScottHelme/securityheaders-bugs#31]
**What happened?**
Warns about duplicate `Referrer-Policy`
https://securityheaders.io/?q=aidanwoods.com&followRedirects=on
<img width="1230" alt="screen shot 2017-06-01 at 22 07 48" src="https://cloud.githubusercontent.com/assets/3288888/26700862/e302d3e6-4716-11e7-912f-914a78d2c1d9.png">

---

**Expected result**
Does not warn when duplicate is valid. In this case [defining multiple referrer policies allows a site to specify a fallback](https://www.w3.org/TR/referrer-policy/#parse-referrer-policy-from-header)

---

This is currently necessary in browsers like Chrome (to achieve a policy that is actually enforced), which do not support the full spec, see: https://bugs.chromium.org/p/chromium/issues/detail?id=627968#c8

**Comment by ScottHelme** [comment]
I thought the correct way to set multiple values was with a comma separated list in the header?

    Referrer-Policy: no-referrer, strict-origin-when-cross-origin

**Comment by aidantwoods** [comment]
That also seems to be valid in Chrome and FireFox (not sure why though because spec doesn't appear[1] to document it). Multiple headers is documented in spec though.

1: (the word *parsing* is a broken link in https://www.w3.org/TR/referrer-policy/#parse-referrer-policy-from-header) so comma delimited may also be valid, I can't tell without the definition though.

I've [bugged](https://github.com/w3c/webappsec-referrer-policy/issues/105) the broken link, multiple headers is definitely valid though (the last header holding a recognised policy being preferred).

---

P.S. multiple CSP headers are also valid (enforced CSP is taken to be the intersection of all given policies), not sure if security-headers will also warn about that?

**Comment by mikewest** [comment]
@aidantwoods: Multiple headers are generally coalesced into a single header with `,` separation (see the "MAY" in https://tools.ietf.org/html/rfc7230#section-3.2.2), so there's no semantic difference between `Referrer-Policy: value1, value2` and

```
Referrer-Policy: value1
Referrer-Policy: value2
```

**Comment by aidantwoods** [comment]
@mikewest ah that's good to know! Just as an aside question – does that mean that if a `,` is present in the CSP header, then things either side would be interpreted as different CSPs (and thus the applied CSP would be their intersection)?

---

@ScottHelme I guess since both ways of specifying fallbacks are valid, warning about the duplicate probably shouldn't happen?

**Comment by mikewest** [comment]
> Just as an aside question – does that mean that if a , is present in the CSP header, then things either side would be interpreted as different CSPs (and thus the applied CSP would be their intersection)?

Yes, see https://w3c.github.io/webappsec-csp/#multiple-policies. That actually opens up some interesting possibilities, like `script-src 'nonce-abc', script-src https://example.com` which confines script execution to both valid origins and valid nonces, which isn't possible with a single policy.

**Comment by aidantwoods** [comment]
> Yes, see https://w3c.github.io/webappsec-csp/#multiple-policies. That actually opens up some interesting possibilities, like `script-src 'nonce-abc', script-src https://example.com` which confines script execution to both valid origins and valid nonces, which isn't possible with a single policy.

Indeed, that is very interesting. I'll have to have more of a play with multiple headers, might be able to add something nice to [SecureHeaders](https://github.com/aidantwoods/SecureHeaders/tree/2.0) to make use of that. (Whitelist restricted `'strict-dynamic'` sounds like a fun experiment for example).

**Comment by ScottHelme** [comment]
Can you test this on the test site for me? 

https://test.securityheaders.com/

**Comment by aidantwoods** [comment]
Looks like the warning is gone :)

https://test.securityheaders.com/?q=aidanwoods.com&followRedirects=on
