### ISSUE TITLE
Is there a WordPress Plugin that can solve the problem?

### ISSUE THREAD

**Issue by Drachsi** [ScottHelme/securityheaders-bugs#33]
With more than 3 million users, WordPress is a powerful platform. Great if there was a Plugin to solve the problems. I tried 2 but the they interfere with the layout.  " HTTP Headers and HTTP Security" both from the WordPress Plugin website.

Hope you can help.
Regards
Drachsi

**Comment by ScottHelme** [comment]
This is something I'm currently considering :)

**Comment by JakeHenshall** [comment]
@Drachsi Hey, have you tried this -> https://wordpress.org/plugins/wp-content-security-policy/

**Comment by sundhaug92** [comment]
I personally use https://wordpress.org/plugins/wp-content-security-policy/ on a site I admin

**Comment by ScottHelme** [comment]
Seems there are options to do this now.
