### ISSUE TITLE
Support for "Expect-Staple" and "Must-Staple"

### ISSUE THREAD

**Issue by alanhuang122** [ScottHelme/securityheaders-bugs#34]
OCSP currently is, to use the common metaphor, akin to a seatbelt that snaps when pulled on, what with soft failing. As you've mentioned in a number of blog posts, Must-Staple and Expect-Staple are ways to fix the problem. I think they should be added to securityheaders.io.

**Comment by thestinger** [comment]
Must-Staple is set in the certificate itself, not as a header. It sets a requirement for revocation checking of that specific certificate.

**Comment by alanhuang122** [comment]
This issue was opened nine months ago. I now know far more than I did when I opened it.

This issue is moot, since Chrome, to my knowledge, never supported "Expect-Staple". And as mentioned, Must-Staple is an x509 extension.
