### ISSUE TITLE
API CORS problems

### ISSUE THREAD

**Issue by schnti** [ScottHelme/securityheaders-bugs#35]
`XMLHttpRequest cannot load https://securityheaders.io/?hide=on&followRedirects=on&q=http://neu.domain.de. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://neu.domain.de' is therefore not allowed access. The response had HTTP status code 405.`

see #17 
https://stackoverflow.com/a/20035319

**Comment by ScottHelme** [comment]
Can you try this now for me?
