### ISSUE TITLE
Don't warn about 'unsafe-inline' in 'script-src' or 'style-src' if combined with hashes or nonces 

### ISSUE THREAD

**Issue by fmeum** [ScottHelme/securityheaders-bugs#37]
Following [CSP Level 2](https://www.w3.org/TR/CSP2/#directive-script-src), 'unsafe-inline' in 'script-src' and 'style-src' will be ignored when paired with at least one hash or nonce source. Since this means that backwards compatibility can be maintained without compromising security for modern user agents, it should probably not generate a warning.

Example report where a warning is shown in the case of 'script-src': https://schd.io/4FPM

**Comment by XhmikosR** [comment]
@ScottHelme: any news about this?

People who aren't very familiar with the CSP specs, get a false impression of a site's grade due to this bug :/

**Comment by fmeum** [comment]
Friendly ping. Spec compliance is important and the fix should not be difficult.

**Comment by bombino** [comment]
Adding a voice to the chorus on this.  CSP-3 is a better solution than CSP-2, but upgrading to it reduces our A+ grade to an A.

**Comment by ScottHelme** [comment]
Can anyone provide a link to a site so I can test this further before I deploy the change? Thanks!

**Comment by fmeum** [comment]
You can use https://hen.ne.ke, where I have deployed unsafe-inline together with hashes sources for both style-src and script-src. As an example page for nonces you could use https://accounts.google.com.

**Comment by ScottHelme** [comment]
Can you take a look on the test site and let me know if you're happy with the fix?

https://test.securityheaders.com/?q=https%3A%2F%2Fhen.ne.ke%2F&hide=on&followRedirects=on

**Comment by fmeum** [comment]
Yes, I can confirm that this issue is fixed. 
There seems to be another issue (related to object-src) with accounts.google.com that you may want to investigate, but I'm not sure whether it it related to the fix: https://test.securityheaders.com/?q=https%3A%2F%2Faccounts.google.com%2F&hide=on&followRedirects=on

**Comment by ScottHelme** [comment]
Ah, was just a typo adding new CSP directives for CSP 3, should be fixed now?

**Comment by fmeum** [comment]
It's fixed now. Thanks!

**Comment by ScottHelme** [comment]
Awesome, it will hit prod in the coming days, I’m fixing up a few other things while I’m here.

**Comment by bombino** [comment]
Nice, can confirm this works for me too!  Thanks for the quick fix.
