### ISSUE TITLE
SSL stack used?

### ISSUE THREAD

**Issue by ArchangeGabriel** [ScottHelme/securityheaders-bugs#38]
It seems securityheaders.io cannot check website using only x25519 as available curve. I suppose it is missing in the used SSL stack?

**Comment by ScottHelme** [comment]
We use the standard install of OpenSSL on Ubuntu, hopefully this will be fixed in our next OS update.

**Comment by ArchangeGabriel** [comment]
OK, I guess you are currently on 16.04, in which case upgrading to 18.04 would indeed solve it. :)
