### ISSUE TITLE
Show a warning if the Expect-CT header is sent over HTTP

### ISSUE THREAD

**Issue by jamieweb** [ScottHelme/securityheaders-bugs#39]
As per section 2.2.2 of the Expect-CT spec, the Expect-CT header SHOULD NOT (RFC2119) be sent over HTTP, similar to the Strict-Transport-Security header.

> 2.2.2.  HTTP Request Type
>
>   Expect-CT Hosts SHOULD NOT include the Expect-CT header field in HTTP
>   responses conveyed over non-secure transport.  UAs MUST ignore any
>   Expect-CT header received in an HTTP response conveyed over non-
>   secure transport.

https://tools.ietf.org/html/draft-ietf-httpbis-expect-ct-02#section-2.2.2

securityheaders.io should display a red warning like it does for HSTS over HTTP if the Expect-CT header is sent over HTTP.

Additionally, a warning could also be shown if the Expect-CT header is present when the server/certificate is not providing valid SCTs.

Thanks

**Comment by ScottHelme** [comment]
These warnings should now be in place on the test site.

https://test.securityheaders.com/
