### ISSUE TITLE
HPKP not valid still reporting A+ 

### ISSUE THREAD

**Issue by niallmerrigan** [ScottHelme/securityheaders-bugs#4]
Checked my site https://www.amisharingstuff.com with new HPKP and securityheaders reports A+ however via report-uri.io tool https://t.co/mcyhlSPUjW it shows invalid. A+ should really be A | (line without a minus ;) )

**Comment by ScottHelme** [comment]
Could you have a tinker around with this if you get chance? 

https://test.securityheaders.io/?q=https%3A%2F%2Fwww.amisharingstuff.com%2F

**Comment by niallmerrigan** [comment]
Looks good...
