### ISSUE TITLE
Apache server header not green/accepted

### ISSUE THREAD

**Issue by FaimMedia** [ScottHelme/securityheaders-bugs#40]
Why does the Apache response header:

    Server: Apache

raise an info message: _This Server header seems to advertise the software being run on the server but you can remove or change this value._

But the nginx response header:

    Server: nginx

is accepted and marked as green.

ServerTokens of Apache that are 'unsafe' include the versions, like:

    Server: Apache/2.4.2 (Unix) PHP/4.2.2 MyMod/1.2

So a `Server` header that only contains `Apache` should also be 'accepted'.

**Comment by ScottHelme** [comment]
This should now be fixed.
