### ISSUE TITLE
Grade cap removed in error when there's an invalid response.

### ISSUE THREAD

**Issue by davepullig** [ScottHelme/securityheaders-bugs#42]
I just tested our site, which had two warnings capping the grade at A. Firstly a warning with my sub-optimal CSP, and secondly a poorly chosen Referrer-Policy. 

I changed the Referrer-Policy to something else, but made an error in the value - this was picked up/flagged correctly but the site then got an A+ grade so it looks like the cap was removed when it shouldn't have been. Just reproduced it deliberately setting the Referrer-Policy to something invalid and it did the same thing.

**Comment by ScottHelme** [comment]
This is now fixed on the test site and will be live soon!
