### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by bpiec** [ScottHelme/securityheaders-bugs#43]
This URL now returns 500: https://api.securityheaders.io/?q=https://securityheaders.io

**Comment by jdgoettsch** [comment]
[The domain changed to securityheaders.com](https://scotthelme.co.uk/security-headers-is-changing-domain-and-branding/).

**Comment by ScottHelme** [comment]
The API was never officially working or supported.

**Comment by bpiec** [comment]
Well, it was introduced in first securityheaders.io post: https://scotthelme.co.uk/introducing-securityheaders-io/

Are you able to make one then?
