### ISSUE TITLE
Which IP range(s) to whitelist for a protected app?

### ISSUE THREAD

**Issue by pkiula** [ScottHelme/securityheaders-bugs#44]
We'd like to conduct header testing for our domain, which is protected from the web at large by IP ranges (among other things). But we'd like to allow the IP range that SecurityHeaders.io uses. Couldn't find this in the FAQ. Any pointers? Thanks.

**Comment by ScottHelme** [comment]
The IP ranges that we use can change depending on our infrastructure and where the test is being conducted from. It's difficult to answer this question in a reliable enough way that the information would continue to be valid!

All I can suggest for now is to request a scan and look at the source IP in your logs at any given time.

**Comment by edmonaft** [comment]
Oh I am in the same boat as pkula. I wonder if there's a specific (in any range) IP i could whitelist to test though. My region is Philippines.

At the moment i am getting this

> Sorry about that...
> The target site took too long to respond and the connection timed out. Try again later.

**Comment by ScottHelme** [comment]
Best thing is to do a scan and look at the current source IP and whitelist that.
