### ISSUE TITLE
Request header for bot protection

### ISSUE THREAD

**Issue by mcurole** [ScottHelme/securityheaders-bugs#45]
We use a system that proactively blocks bots which blocks your scan. Are there any request headers we can use to disable this protection from your scan?

**Comment by ScottHelme** [comment]
Hey @mcurole, we don't set a particular header but this should be easy enough to do, let me have a look at what we should set.

**Comment by mcurole** [comment]
Most bots use a specific user-agent header

*Mark Curole*
Lead Engineer, Technology Planning
Shaw Industries Group Inc.
616 E Walnut Ave
Dalton, GA 30721
Email: mark.curole@shawinc.com <mcurole@shawinc.com>  Office: 706-532-3817

On Sun, Apr 22, 2018 at 6:31 AM, Scott Helme <notifications@github.com>
wrote:

> Hey @mcurole
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcurole&d=DwMCaQ&c=7f1YSuqIGbgL_Gzm5POfng&r=BkGsT0yYlUNvmzgepw9bKodQsBqWG3PGSKbmGQNv2L4&m=97KDlOxsMX80uBpLUjmqpen7NRO2Rre6WJB1ccPJmnE&s=CIgEB4ThH04TYLJfq7xgP9ltuej2mCQnGBEjWeeMjbk&e=>,
> we don't set a particular header but this should be easy enough to do, let
> me have a look at what we should set.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_securityheaders_securityheaders-2Dbugs_issues_45-23issuecomment-2D383371111&d=DwMCaQ&c=7f1YSuqIGbgL_Gzm5POfng&r=BkGsT0yYlUNvmzgepw9bKodQsBqWG3PGSKbmGQNv2L4&m=97KDlOxsMX80uBpLUjmqpen7NRO2Rre6WJB1ccPJmnE&s=OWn1Sc8hLt18nZR9wziD8ATYT2jEC2V63IByJLNjlZk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_Adb2Km49YA98IES3t3A2DKJKN8insy7Dks5trFwFgaJpZM4TdZTX&d=DwMCaQ&c=7f1YSuqIGbgL_Gzm5POfng&r=BkGsT0yYlUNvmzgepw9bKodQsBqWG3PGSKbmGQNv2L4&m=97KDlOxsMX80uBpLUjmqpen7NRO2Rre6WJB1ccPJmnE&s=TMTuXnVHstd4XtRdNtU9lHY2TLMXEuTyJDJPGtQR6iM&e=>
> .
>

-- 
**********************************************************
Privileged 
and/or confidential information may be contained in this message. If you 
are not the addressee indicated in this message (or are not responsible for 
delivery of this message to that person) , you may not copy or deliver this 
message to anyone. In such case, you should destroy this message and notify 
the sender by reply e-mail.
If you or your employer do not consent to 
Internet e-mail for messages of this kind, please advise the sender.
Shaw 
Industries does not provide or endorse any opinions, conclusions or other 
information in this message that do not relate to the official business of 
the company  or its subsidiaries.

**********************************************************

**Comment by ScottHelme** [comment]
We're going to stick with a Chrome based UA string.
