### ISSUE TITLE
Show warning if Expect-CT uses wrong syntax (semicolon)

### ISSUE THREAD

**Issue by hannob** [ScottHelme/securityheaders-bugs#46]
The Expect-CT header separates different values with a comma. This is different from many other security-related headers (HSTS, CSP), but it's actually what the spec says and it's also closer to HTTP standards, see discussions here:
https://github.com/httpwg/http-extensions/issues/318#issuecomment-294369176
https://github.com/httpwg/http-extensions/pull/327

It would be good to show a warning for noncompliant Expect-CT headers, e.g. something like:
 Expect-CT: enforce; max-age=63072000
would be invalid, it should be
 Expect-CT: enforce, max-age=63072000

**Comment by ScottHelme** [comment]
This change will land today.
