### ISSUE TITLE
Feature Request: remove site if we forgot to use "Hide results"

### ISSUE THREAD

**Issue by Aumnia** [ScottHelme/securityheaders-bugs#47]
Not sure how best to accomplish this but I'm probably not going to be the last person to forget to use the "Hide results" feature and then wish a site wasn't listed on the home page...

**Comment by ScottHelme** [comment]
This is really difficult to achieve as we'd need to verify your ownership or control of the domain to have the results removed. Without some kind of verification the feature would be too easy to abuse. 

The 'hide results' option was offered to allow sites the opportunity to not appear on the home page but even if you do, results don't remain there for very long. If there is a solution you can suggest I'd be happy to consider it but right now we don't have plans to implement this feature.
