### ISSUE TITLE
Same-Site cookie : add verification and recommandation 

### ISSUE THREAD

**Issue by OlivierJaquemet** [ScottHelme/securityheaders-bugs#50]
Now that same Same-Site cookie is supported by major browsers, and because this feature is backward compatible with browser not implementing it...
https://twitter.com/Scott_Helme/status/1009010719877226496?s=03
https://caniuse.com/#feat=same-site-cookie-attribute

...maybe you could consider 
1. adding a verification of SameCookie by securityheaders.com
2. adding a recommandation/explanation wih a link to your existing blog post :
linking to https://scotthelme.co.uk/csrf-is-dead/
(and maybe this one to link
https://scotthelme.co.uk/hardening-your-http-response-headers/ )

**Comment by ScottHelme** [comment]
This checks should land today.

**Comment by OlivierJaquemet** [comment]
Thanks @ScottHelme .
