### ISSUE TITLE
Add check for header `Cross-Origin-Window-Policy`

### ISSUE THREAD

**Issue by craigfrancis** [ScottHelme/securityheaders-bugs#51]
The `Cross-Origin-Window-Policy` header is now supported in Safari Technology Preview 59 (and hopefully other browsers soon):

https://github.com/whatwg/html/issues/3740
https://groups.google.com/a/chromium.org/forum/#!topic/isolation-policy/zueJF9ad20g
https://www.arturjanc.com/cross-origin-infoleaks.pdf
https://webkit.org/blog/8332/release-notes-for-safari-technology-preview-59/

e.g.

    Cross-Origin-Window-Policy: Deny
    Cross-Origin-Window-Policy: Allow
    Cross-Origin-Window-Policy: Allow-PostMessage

**Comment by gapple** [comment]
Support has now been removed in Safari Technology Preview 67
https://webkit.org/blog/8419/release-notes-for-safari-technology-preview-67/
