### ISSUE TITLE
Add check for header `Feature-Policy`

### ISSUE THREAD

**Issue by craigfrancis** [ScottHelme/securityheaders-bugs#53]
The `Feature-Policy` header (and `allow` attribute on <iframe>'s) is beginning to get support in Chrome (as of ~60), and hopefully other browsers soon:

https://wicg.github.io/feature-policy/
https://developers.google.com/web/updates/2018/06/feature-policy
https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/feature_policy/feature_policy.cc?q=GetDefaultFeatureNameMap&sq=package:chromium&dr=CSs&l=138

e.g.

    Feature-Policy:
        accelerometer: 'none';
        ambient-light-sensor: 'none';
        camera: 'none';
        encrypted-media: 'none';
        fullscreen: 'none';
        geolocation: 'none';
        gyroscope: 'none';
        magnetometer: 'none';
        microphone: 'none';
        midi: 'none';
        payment: 'none';
        speaker: 'none';
        sync-xhr: 'self';
        usb: 'none';
        vr: 'none';

**Comment by craigfrancis** [comment]
I think this one can be closed now, as it was added on the 16th July:

https://scotthelme.co.uk/a-new-security-header-feature-policy/

Although the list of example Feature Policy directives on that page probably should be updated, to match those currently being provided by Chrome...

These have either been removed, or haven't been implemented yet:
- notifications
- push
- vibrate

And these have been added:
- accelerometer
- ambient-light-sensor
- encrypted-media
- usb
- vr

**Comment by ghost** [comment]
I wonder whether there isn't a small issue with the current implementation in the form of a warning reading `We detected an invalid directive, "".` It seems to appear even when the policy is, as far as I can tell, devoid of empty directives.

From a purely visual standpoint, quoted sources such as _'none'_ appear in italics for `Content-Security-Policy`, but not for `Feature-Policy`.

**Comment by ScottHelme** [comment]
This will land today, including better policy validation and syntax highlighting.
