### ISSUE TITLE
Consider removing X-XSS-Protection due to its security holes, browsers defaulting it, and instead recommend CSP

### ISSUE THREAD

**Issue by laukstein** [ScottHelme/securityheaders-bugs#56]
Seems X-XSS-Protection has no use today when having CSP support.

> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
> these protections are largely unnecessary in modern browsers when sites implement a strong Content-Security-Policy that disables the use of inline JavaScript ('unsafe-inline')

Firefox is not going to support `X-XSS-Protection` [#528661](https://bugzilla.mozilla.org/show_bug.cgi?id=528661#c56).
Chrome is defaulting to `X-XSS-Protection: 1; mode=block` [#654794](https://bugs.chromium.org/p/chromium/issues/detail?id=654794).
Microsoft breaks `X-XSS-Protection` support:
* https://www.bleepingcomputer.com/news/security/microsoft-edges-xss-filter-appears-to-be-broken/
* https://portswigger.net/daily-swig/xss-protection-disappears-from-microsoft-edge

**Comment by laukstein** [comment]
@ScottHelme fyi Microsoft just retired XSS Filter support.
> https://www.bleepingcomputer.com/news/microsoft/windows-10-insider-build-17723-redstone-5-and-build-18204-redstone-6-released-heres-whats-new/
> XSS Filter has also been retired in favor of Content Security Policies.

Official "Retired XSS Filter in Microsoft Edge" announcement https://blogs.windows.com/windowsexperience/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204/

**Comment by leoliu** [comment]
Looks like Chrome is deprecating and removing the xss auditor. https://www.chromium.org/developers/design-documents/xss-auditor

**Comment by ScottHelme** [comment]
This change will land today.
