### ISSUE TITLE
Support cookies

### ISSUE THREAD

**Issue by bpiec** [ScottHelme/securityheaders-bugs#58]
I noticed that securityheaders does not support cookies, is there an option to add it?

This results in an infinite redirects for some sites. For example pick https://www.bankmillennium.pl/osobiste2/Retail/Login/MulticodeRequest
When I test it I get a "too many redirects" message: https://securityheaders.com/?q=https%3A%2F%2Fwww.bankmillennium.pl%2Fosobiste2%2FRetail%2FLogin%2FMulticodeRequest&hide=on&followRedirects=on
When I disable "follow redirects" it outputs the correct results but with "R" grade: https://securityheaders.com/?q=https%3A%2F%2Fwww.bankmillennium.pl%2Fosobiste2%2FRetail%2FLogin%2FMulticodeRequest&hide=on

I can see the same results ("The page isn’t redirecting properly") when I disable cookies in Firefox so that's why I am thinking it is the lack of cookie support.

**Comment by ScottHelme** [comment]
This seems like a very limited problem compared to the considerations of enabling cookies.
