### ISSUE TITLE
Trim input url - otherwise unnecessary error produced

### ISSUE THREAD

**Issue by wentylos** [ScottHelme/securityheaders-bugs#6]
It would be great if you could trim input url. If i put white character before or after url I receive unnecessary error. Usually by copying url from email or somewhere.

Error message is: Sorry about that... Something went wrong there! Maybe check the URL and try again? 6 Could not resolve host: www.eujuicers.com 

Hope it's really easy fixing it, could help someone in the future.

**Comment by ScottHelme** [comment]
This is fixed on the test site and should hit live 'soon'. 

https://test.securityheaders.io
