### ISSUE TITLE
Feature Suggestion - Detect if Running Unsupported Web Server

### ISSUE THREAD

**Issue by sbirdsill** [ScottHelme/securityheaders-bugs#60]
Since your site is able to detect the web server advertised in the header, would it be beneficial to report if the server is running an unsupported web server such as IIS 6.0 or Apache 2.2.x?

It may defeat the purpose of telling the user to hide the Server header, but maybe it will stress the importance of hiding it, especially if you happen to be running a web server that is no longer receiving security patches.

**Comment by ScottHelme** [comment]
I feel this is out of scope for the purpose of the project.
