### ISSUE TITLE
Invalid directive for Feature-Policy

### ISSUE THREAD

**Issue by ghost** [ScottHelme/securityheaders-bugs#61]
I hope I am not missing the obvious and embarrassing myself publicly, here, but I have noticed a warning in our reports that _seems_ to be spurious. Even though our “Feature-Policy” header is, as far as I can tell, [formed properly](https://securityheaders.com/?q=https%3A%2F%2Fcircule.cc%2F&hide=on&followRedirects=on), the site always displays the following warning:

> We detected an invalid directive, “”.

There is also a slight cosmetic bug: “none” declarations for Content Security Policies are displayed in italics, but the very same declarations are displayed without styling in the Feature Policy entry.

**Comment by ScottHelme** [comment]
We now have detection for empty directives, usually caused by a trailing semicolon on the end of a policy that shouldn't be there. 

We will also have syntax highlighting later today. 

If you still have issues please open the ticket again.
