### ISSUE TITLE
Server Header should be flagged for AmazonS3 server headers

### ISSUE THREAD

**Issue by IAmATeaPot418** [ScottHelme/securityheaders-bugs#66]
Hi Scott,

For serverless applications I see that security headers is incorrectly flagging the server header as being changed. For example, a site hosted on S3 will have the server header AmazonS3 by default. While this can really only be removed by fronting S3 with a WAF or possibly modifying headers with lambda, do you think it should still be flagged as a default server header.

Thanks!

**Comment by ScottHelme** [comment]
This will be covered in the release today.
