### ISSUE TITLE
False results from cloudflare sites.

### ISSUE THREAD

**Issue by no-replies** [ScottHelme/securityheaders-bugs#67]
False results from cloudflare proxied sites due to HTTP/1.1

Need a way to whitelist IP's, user agent.

**Comment by no-replies** [comment]
seems that Cloudflare is blocking whatever host, IP, or user agent - need a way to whitelist

**Comment by ScottHelme** [comment]
I've been scanning many Cloudflare protected sites, including my own, without error. If you are still seeing this error you may need to check your Cloudflare settings if it's your own site.
