### ISSUE TITLE
Offline feature for developers

### ISSUE THREAD

**Issue by AndyMDoyle** [ScottHelme/securityheaders-bugs#7]
I may be going about it the wrong way, but I can't help feel it would be nice for developers if they could run some manual headers through the site to get a summary report.

Headers could be copied/pasted from CURL or something like Chrome dev tools, and pasted as a lump of text, parsed, and treated as if the headers had been obtained properly during your HTTP check.

It may save someone from making a syntax error in their CSP/HPKP/other headers and going live with the wrong headers.

What does everyone think?

**Comment by ScottHelme** [comment]
I may look at this in the future but it's not something on my radar right now. I will close this issue for the time being.
