### ISSUE TITLE
HSTS max-age not recognised

### ISSUE THREAD

**Issue by dimaqq** [ScottHelme/securityheaders-bugs#76]
Here's the result of my current attempt:

<img width="808" alt="Screenshot 2020-05-12 at 13 43 31" src="https://user-images.githubusercontent.com/662249/81640001-6cb42680-9458-11ea-8916-b08775e8756b.png">

So I have `max-age` but I don't have `max-age`?

Or am I just blind 🕶️ 👀 ❓ 

I've actually taken the value from the recommendation that securityheader.com give for the bad, broken, insecure sites:

<img width="643" alt="Screenshot 2020-05-12 at 13 56 34" src="https://user-images.githubusercontent.com/662249/81640009-7047ad80-9458-11ea-971b-ec14e97dfcfb.png">

**Comment by dimaqq** [comment]
OMG I am blind after all... Let's call it a copy-paste error... :hides:

**Comment by ScottHelme** [comment]
Glad I could help!! 😂
