### ISSUE TITLE
Highlight of feature policy incorrect for xr-spatial-tracking

### ISSUE THREAD

**Issue by smarek** [ScottHelme/securityheaders-bugs#83]
![2020-08-12-103328_1176x53_scrot](https://user-images.githubusercontent.com/384824/89994371-52bcf680-dc88-11ea-9dbc-3371ef2ed5bf.png)

highlighted part should be `xr-spatial-tracking` not just the `xr` part

I haven't tested all the features in https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md#standardized-features
so this might affect more

**Comment by Peneheals** [comment]
I can also confirm this lil' bug :)

**Comment by ScottHelme** [comment]
Try now for me, just deployed a fix!

**Comment by Peneheals** [comment]
It works, thank you!

<img width="178" alt="xr_full_bold" src="https://user-images.githubusercontent.com/7722456/117427134-0061eb00-af25-11eb-8269-594748982bf0.png">
