### ISSUE TITLE
Does not read Content Security Policy from html meta tag

### ISSUE THREAD

**Issue by Zaita** [ScottHelme/securityheaders-bugs#93]
When scanning and using HTML meta tag for the CSP, this does not get detected.

![image](https://user-images.githubusercontent.com/1491276/108915074-3cf5a880-7691-11eb-8672-d1e061c1b737.png)

**Comment by fzipi360** [comment]
This is still a problem. Any thoughts here? Can this be checked?

**Comment by ScottHelme** [comment]
Hi,

We only scan HTTP response headers and not meta tags in the page, this is why the policy will not be picked up!

Cheers, 

Scott.
